### ISSUE TITLE
UE version: 5.4.2 can not  dump

### ISSUE THREAD

**Issue by 350030173** [hackcatml/frida-ue4dump#12]
game url :https://apkcombo.com/zh/rooftops-parkour-freerun/com.GreenGoGames.RooftopPrakourFreerun/
![1](https://github.com/user-attachments/assets/50c191af-f47b-45c9-9855-ce050d46600a)

**Comment by hackcatml** [comment]
Hello, I updated the script for that game.

**Comment by 350030173** [comment]
nice
