### ISSUE TITLE
Black Clover Mobile support

### ISSUE THREAD

**Issue by HazardVS** [hackcatml/frida-ue4dump#5]
Hi! Can you add Black Clover Mobile please? Global and JP version if it's possible please. Thank you very much!

**Comment by hackcatml** [comment]
Hi, I've added dump for the KR and JP versions. check it out!

**Comment by HazardVS** [comment]
Thank you very much! I have a question:

I run `frida -Ul script.js com.vic.bc.kr` but it doesn't found the process. I have frida-server running and all okay.

**Comment by hackcatml** [comment]
That's weird. That error means it couldn't find the module named "libUE4.so".
But when I test the script, it works fine.
![image](https://github.com/hackcatml/frida-ue4dump/assets/75507443/691023c1-385c-44dd-b87c-5cbddb8817bd)

Check the module existence by following frida command after attaching to the process.
`Process.findModuleByName("libUE4.so")`
It should show you the module information.
![image](https://github.com/hackcatml/frida-ue4dump/assets/75507443/b3384200-4942-4d42-9f9a-96341edecdb4)

**Comment by HazardVS** [comment]
Hi, thanks for the reply.

`Process.findModuleByName("libUE4.so")` gives me null.
![112082b08d3a75e7c693a72442249797](https://github.com/hackcatml/frida-ue4dump/assets/164770563/d61c2b85-7567-4847-8fbe-495552a1e1f6)

**Comment by hackcatml** [comment]
I checked the emulators (Nox, LDPlayer) and confirmed that it's not working on them. 
Sadly, frida can't find the module

**Comment by Chensem** [comment]
> Hi, thanks for the reply.
> 
> `Process.findModuleByName("libUE4.so")` gives me null. ![112082b08d3a75e7c693a72442249797](https://private-user-images.githubusercontent.com/164770563/317270607-d61c2b85-7567-4847-8fbe-495552a1e1f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyOTYyNjksIm5iZiI6MTcxNDI5NTk2OSwicGF0aCI6Ii8xNjQ3NzA1NjMvMzE3MjcwNjA3LWQ2MWMyYjg1LTc1NjctNDg0Ny04ZmJlLTQ5NTU1MmExZTFmNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyOFQwOTE5MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MTYwM2YzYjE4ZTQwMDQwNmZlNDY3NzA1NmY1MzdlZjI2NGZhMmQ3ZmRlY2VmZjkxNGQxZDcwZDI0ODFjYTU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DL9ddAGlS3b80FrcXS0TzeSt2qlu9QCTNKiJmMv6tOM)
> 
> Edit: I checked `/data/app/com.vic.bc.kr-1/lib/arm64` and libUE4.so is there. ![23f6643124e701f36860034e1b9631fc](https://private-user-images.githubusercontent.com/164770563/317294072-f95686a4-89dc-4e1d-a2d4-91aa81a573c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyOTYyNjksIm5iZiI6MTcxNDI5NTk2OSwicGF0aCI6Ii8xNjQ3NzA1NjMvMzE3Mjk0MDcyLWY5NTY4NmE0LTg5ZGMtNGUxZC1hMmQ0LTkxYWE4MWE1NzNjOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyOFQwOTE5MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNmVjODBkODY0ZWNkNmU1MGM1ODkwMjU3MTliODIzYTMzOGRkZjNmMjcwMmYyZDRlMDYwYzI1YzEwMmU1Mzk0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-rS4I-coouYJE5wwO9fUZIIrKiVoW3kWJZMx_l3c5B4)

You should start the game with frida options `frida -U -f com.package.name --realm=emulated` , then you will find the module `libUE4.so`

**Comment by hackcatml** [comment]
> > Hi, thanks for the reply.
> > `Process.findModuleByName("libUE4.so")` gives me null. ![112082b08d3a75e7c693a72442249797](https://private-user-images.githubusercontent.com/164770563/317270607-d61c2b85-7567-4847-8fbe-495552a1e1f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyOTYyNjksIm5iZiI6MTcxNDI5NTk2OSwicGF0aCI6Ii8xNjQ3NzA1NjMvMzE3MjcwNjA3LWQ2MWMyYjg1LTc1NjctNDg0Ny04ZmJlLTQ5NTU1MmExZTFmNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyOFQwOTE5MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MTYwM2YzYjE4ZTQwMDQwNmZlNDY3NzA1NmY1MzdlZjI2NGZhMmQ3ZmRlY2VmZjkxNGQxZDcwZDI0ODFjYTU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DL9ddAGlS3b80FrcXS0TzeSt2qlu9QCTNKiJmMv6tOM)
> > Edit: I checked `/data/app/com.vic.bc.kr-1/lib/arm64` and libUE4.so is there. ![23f6643124e701f36860034e1b9631fc](https://private-user-images.githubusercontent.com/164770563/317294072-f95686a4-89dc-4e1d-a2d4-91aa81a573c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyOTYyNjksIm5iZiI6MTcxNDI5NTk2OSwicGF0aCI6Ii8xNjQ3NzA1NjMvMzE3Mjk0MDcyLWY5NTY4NmE0LTg5ZGMtNGUxZC1hMmQ0LTkxYWE4MWE1NzNjOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyOFQwOTE5MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNmVjODBkODY0ZWNkNmU1MGM1ODkwMjU3MTliODIzYTMzOGRkZjNmMjcwMmYyZDRlMDYwYzI1YzEwMmU1Mzk0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-rS4I-coouYJE5wwO9fUZIIrKiVoW3kWJZMx_l3c5B4)
> 
> You should start the game with frida options `frida -U -f com.package.name --realm=emulated` , then you will find the module `libUE4.so`

Thanks, I updated README.
