### ISSUE TITLE
Wuthering Waves Issue

### ISSUE THREAD

**Issue by hayate001** [hackcatml/frida-ue4dump#8]
I run frida -Ul script.js com.kurogame.wutheringwaves.global but it doesn't found the process. My frida-server running , and i try to open game manualy but still got the same error
Failed to spawn: unable to find process with name 'com.kurogame.wutheringwaves.global'
My devices is PX 7

**Comment by hackcatml** [comment]
Hello, should use `-N` option with game's package name.
`frida -Ul script.js -N com.kurogame.wutheringwaves.global`

**Comment by hayate001** [comment]
thank for update sir , but now i got dumsdk offset the same . too many function same offfset 
![Untitled](https://github.com/hackcatml/frida-ue4dump/assets/56855590/735ac7fc-470a-46b9-9b59-443d68b82fa2)

**Comment by hackcatml** [comment]
All blueprint functions have the same offset(`UObject::ProcessInternal(UObject*, FFrame&, void*)`)
If you want to observe blueprint functions, need to hook `UObject::ProcessEvent(UFunction*, void*)`
